apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "mysqllogs.fullname" . }}-logdir-pvc"
  labels:
{{ include "mysqllogs.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

