apiVersion: v1
data:
  logrotate.conf: |
    "{{ .Values.proxysql.config.eventsDir }}/{{ .Values.proxysql.config.eventsFile }}.????????" {
      rotate {{ .Values.logrotate.config.rotate }}
      copytruncate
      size {{ .Values.logrotate.config.size }}
      missingok
      compress
    }   
kind: ConfigMap
metadata:
  name: "{{ include "mysqllogs.fullname" . }}-logrotate-config"
  labels:
{{ include "mysqllogs.labels" . | indent 4 }}

