apiVersion: v1
kind: Service
metadata:
  name: "{{ include "mysqllogs.fullname" . }}-service"
  labels:
{{ include "mysqllogs.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    app.kubernetes.io/name: {{ include "mysqllogs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
