apiVersion: v1
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"
    admin_variables=
    {
            admin_credentials="proxysql-admin:adminpassw0rd"
    }
    mysql_variables=
    {
            eventslog_filename="/var/log/proxysql/queries"
            eventslog_filesize=1073741824
            eventslog_format=2
            monitor_username="proxysql"
            monitor_password="proxysqlpassw0rd"
            server_version="5.7.22-standard"
    }
    mysql_replication_hostgroups = ()
    mysql_servers =
    (
            { address="mysql" , port=3306 , hostgroup=10, max_connections=100 },
    )
    mysql_users = ()
    mysql_query_rules =
    (
            {
                    rule_id=1
                    active=1
                    match_digest="."
                    log=1
                    apply=0
            }
    )
kind: ConfigMap
metadata:
  name: proxysql-configmap-v6
  namespace: default
