kind: PersistentVolume
apiVersion: v1
metadata:
  name: proxysql-helm-datadir
  labels:
    type: local
    app: querylogs
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/proxysql-helm-data"
