apiVersion: v1
data:
  logrotate.conf: |
    "/var/log/proxysql/queries.????????" {
      rotate 5
      copytruncate
      size 10M
      missingok
      compress
    }   
kind: ConfigMap
metadata:
  name: logrotate-configmap-v5
  namespace: default

