apiVersion: v1
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"
    admin_variables=
    {
            admin_credentials="proxysql-admin:adminpassw0rd"
    }
    mysql_variables=
    {
            eventslog_filename="/var/log/proxysql/queries"
            eventslog_format=2
            monitor_username="proxysql"
            monitor_password="proxysqlpassw0rd"
            server_version="proxysql-0.0.8"
    }
    mysql_replication_hostgroups = ()
    mysql_servers =
    (
            { address="mysql" , port=3306 , hostgroup=10, max_connections=100 },
    )
    mysql_users = ()
    mysql_query_rules =
    (
            {
                    rule_id=100
                    active=1
                    match_pattern="^SELECT .*"
                    destination_hostgroup=10
                    apply=1
            },
            {
                    rule_id=200
                    active=1
                    match_pattern=".*"
                    destination_hostgroup=10
                    apply=1
            },
            {
                    rule_id=300
                    active=1
                    match_pattern=".*"
                    log=1
                    apply=1
            }
    )
kind: ConfigMap
metadata:
  creationTimestamp: "2019-07-04T04:45:44Z"
  name: proxysql-configmap-v5
  namespace: default
  resourceVersion: "238071"
  selfLink: /api/v1/namespaces/default/configmaps/proxysql-configmap-v3
  uid: fac3f667-3858-47a7-878f-37dcd7d8a8ad
