apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxysql
  labels:
    app: proxysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxysql
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: proxysql
        tier: frontend
    spec:
      restartPolicy: Always
      containers:
      - image: proxysql:0.0.8
        name: proxysql
        volumeMounts:
        - name: proxysql-config
          mountPath: /etc/proxysql/proxysql.cnf
          subPath: proxysql.cnf
        - name: proxysql-lib
          mountPath: /var/lib/proxysql
        - name: proxysql-log
          mountPath: /var/log/proxysql
        ports:
        - containerPort: 6033
          name: proxysql-mysql
        - containerPort: 6032
          name: proxysql-admin
      volumes:
      - name: proxysql-config
        configMap:
          name: proxysql-configmap-v5
      - name: proxysql-lib
        persistentVolumeClaim:
          claimName: proxysql-datadir-claim
      - name: proxysql-log
        persistentVolumeClaim:
          claimName: proxysql-logdir-claim
---
apiVersion: v1
kind: Service
metadata:
  name: proxysql
  labels:
    app: proxysql
    tier: frontend
spec:
  type: NodePort
  ports:
    - nodePort: 30033
      port: 6033
      name: proxysql-mysql
    - nodePort: 30032
      port: 6032
      name: proxysql-admin
  selector:
    app: proxysql
    tier: frontend        
