kind: PersistentVolume
apiVersion: v1
metadata:
  name: proxysql-datadir
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/proxysql-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxysql-datadir-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

