apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  names: "{{ include "mysql-query-logs.fullname" . }}-logdir-pvc"
  labels:
{{ include "mysql-query-logs.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

