apiVersion: v1
data:
  logrotate.conf: |
    {{ .Values.proxysql.config.eventsDir }} {
      rotate {{ .Values.logrotate.config.rotate }}
      copytruncate
      size {{ .Values.logrotate.config.size }}
      missingok
      compress
    }   
kind: ConfigMap
metadata:
  name: "{{ include "mysql-query-logs.fullname" . }}-logrotate-config"
  namespace: default

