apiVersion: v1
data:
  proxysql.cnf: |
    {{ .Values.proxysql.config.eventsDir }} {
      rotate {{ .Values.logrotate.config.rotate }}
      copytruncate
      size {{ .Values.logrotate.config.size }}
      missingok
      compress
    }   
kind: ConfigMap
metadata:
  name: logrotate-configmap
  namespace: default

